;(function() {
	window._1gam.game = window._1gam.game || {};
	window._1gam.constants = {};

	_1gam.constants = {
		GRAVITY: 1200,
		PLAYER_SPEED: 20,
		PLAYER_SPEED_START_MULTIPLIER: 3,
		PLAYER_SPEED_START_THRESHOLD: 130,
		PLAYER_DRAG: 800,
		PLAYER_MAX_SPEED: 400,
		PLAYER_MAX_FALL_SPEED: 350,
		PLAYER_JUMP_FORCE: -400,
		PLAYER_JUMP_HOLD_FORCE: -16,
		PLAYER_JUMP_HOLD_THRESHOLD: 300,
		PLAYER_JUMP_INTERVAL: 500,
		PLAYER_SPRITE_KEY: "grape",
		PLAYER_SLOWDOWN_ANIM_THRESHOLD: 100,
		PLAYER_IDLE_THRESHOLD: 2,
		PLAYER_JUMP_FORGIVENESS_THRESHOLD: 150
	};
})();
